# -------------------------------------------------------------------------------------------------
# Redis Connection Settings
# -------------------------------------------------------------------------------------------------

Redis:
  Host: ""
  Port: 6379
  User: ""
  Password: ""

# -------------------------------------------------------------------------------------------------
# MongoDB Connection Settings
# -------------------------------------------------------------------------------------------------

MongoDB:
  Connection_String: ""
  Database: "flocksystem"

# -------------------------------------------------------------------------------------------------
# MOTD Settings, you can use a minimessage-like format
# -------------------------------------------------------------------------------------------------

MOTD: "     Â§8â–¬Â§2â–¬Â§aâ–¬Â§r <gradient=#3aa629,#38d620><bold>ZFLOCKII.DE</bold></gradient> Â§7âœ¤ Â§8[Â§fÂ§lEVENTSÂ§8] Â§7âœ¤ Â§8[Â§fÂ§l1.21.XÂ§8] Â§aâ–¬Â§2â–¬Â§8â–¬\n                  Â§8â–¬ <gradient=#347a2a,#1aa605>á´›á´¡Éªá´›á´„Êœ.á´›á´ /á´¢FÊŸá´á´„á´‹ÉªÉª</gradient> Â§8â–¬"
Maintenance_MOTD: "     Â§8â–¬Â§4â–¬Â§câ–¬Â§r <gradient=#c62929,#d62020><bold>ZFLOCKII.DE</bold></gradient> Â§7âœ¤ Â§8[Â§cÂ§lWARTUNGÂ§8] Â§7âœ¤ Â§8[Â§cÂ§l1.21.5Â§8] Â§câ–¬Â§4â–¬Â§8â–¬\n     Â§8â–¬ <gradient=#7a2a2a,#a60505>Â§cGrund: %reason% | Bis: %end_time%</gradient> Â§8â–¬"

# -------------------------------------------------------------------------------------------------
# Tablist Settings, you can use a minimessage-like format
# -------------------------------------------------------------------------------------------------

Tablist:
  Header:
    - ''
    - " Â§ağŸ—¡ Â§lÂ§nEvent-NetzwerkÂ§r Â§ağŸ—¡"
    - 'Â§aá´¢Ò“ÊŸá´á´„á´‹ÉªÉª.á´…á´‡'
    - ''
    - 'Â§7á´…á´‡Ê€á´¢á´‡Éªá´› Â§f%online% Â§7sá´˜Éªá´‡ÊŸá´‡Ê€ á´ á´‡Ê€Ê™á´œÉ´á´…á´‡É´'
    - ''
  Footer:
    - ''
    - ' Â§aÂ§ná´›á´¡Éªá´›á´„ÊœÂ§r                       Â§aÂ§ná´…ÉªÑ•á´„á´Ê€á´…Â§r  '
    - '    Â§fá´›á´¡Éªá´›á´„Êœ.á´›á´ /á´¢Ò“ÊŸá´á´„á´‹ÉªÉª        Â§fá´…Éªsá´„á´Ê€á´….á´¢Ò“ÊŸá´á´„á´‹ÉªÉª.á´…á´‡     '
    - ''

# -------------------------------------------------------------------------------------------------
# The formats used in the {timestamp} and {location} variables. For help with timestamp, see:
# https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
# -------------------------------------------------------------------------------------------------
Timestamp_Format: "dd.MM.yyyy HH:mm:ss"
Location_Format: "{world} [{x}, {y}, {z}]"

# -------------------------------------------------------------------------------------------------
# What commands should trigger the main plugin command group?
#
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ flock ]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied 
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages. You can manually use it with
# {plugin_prefix} variable anywhere.
# -------------------------------------------------------------------------------------------------
Prefix: "&8&lâ½ &a&lFlockSystem &8&lâ€¢&7 "

# -------------------------------------------------------------------------------------------------
# Time of some plugin's operations is measured. You can also use the LagCatcher class to invoke
# this feature. We log a console message if an operation takes over the time below (milliseconds). 
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# List of section names that will print informative messages about their features.
# The Debugger class utilizes this key and will only print messages for sections enabled below.
# -------------------------------------------------------------------------------------------------
Debug: [ ]

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1